config/routes.rb
Rails.application.routes.draw do

  resources :logbenefitsfinals do
     collection do
       post 'saveLogFinal', to: "logbenefitsfinals#saveLogFinal"
     end
   end
  resources :familiartrabajadors
  resources :asignarmultiplebeneficios do
    collection do
      get 'get_contacts', to: "asignarmultiplebeneficios#get_contacts"
    end

    collection do
      get 'get_trabajadorporobra', to: "asignarmultiplebeneficios#get_trabajadorporobra"
    end
  end

  resources :logloans
  resources :employees
  resources :assignbenefits
  resources :areabenefits do
    member do
      get :is_active
    end
  end
  resources :loanformularies do
    member do
      get :accept
      get :refuse
      get :filtrar
    end
  end


  devise_for :lydusers
  get '/ld/index', to: 'ld#index'
  get 'ld/crudpannel', to: 'ld#crudpannel'
  get 'ld/beneficiospannel', to: 'ld#beneficiospannel'
  get 'ld/reportspannel', to: 'ld#reportspannel'
  get 'ld/userspannel', to: 'ld#userspannel'
  get 'ld/download_pdf', to: 'ld#download_pdf'
  root to: 'ld#index'
  #get 'asformularies/newseg', to: 'asformularies#newseg', as: 'newseg'


  resources :benefits do
    member do
      get :is_active
    end
  end

  resources :obras
  resources :logas
  resources :epcformularies
  resources :asformularies do
    member do
      get :newseg
      get :checkrut
    end
    collection do
      get 'search', to: "asformularies#search"
      get 'get_benefits', to: "asformularies#get_benefits"
    end
  end

  resources :aspcategories do
    member do
      get :is_active
    end
  end

  resources :users

  resources :pages do
    get :download_pdf
  end


  get '/benefitPanel', to: 'pages#benefitPanel'
  #post '/benefitPanel' => 'pages#indexBenefitPerName'
  post '/logBeneficiosCheckAsistencia', to: 'pages#logBeneficiosCheckAsistencia'
  post '/indexBenefitPerName', to: 'pages#indexBenefitPerName'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/asformulary.rb
class Asformulary < ApplicationRecord
  #belongs_to :user
  belongs_to :lyduser
  belongs_to :aspcategory
  belongs_to :benefit
  has_many :epcformularies, :dependent => :destroy

  #before_create :set_atencion_id

  validate :input_atributos

  after_create :crear_log_A
  after_update :crear_log_B

  def self.search(search)
    if search
      where('nombre_atendido LIKE ? or apellido_paterno LIKE ? or apellido_materno LIKE ? or rut_atendido LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%","%#{search}%")
    else
      where('nombre_atendido LIKE ?', nil)
    end
  end

  def input_atributos
    if rut_atendido.present?
      dv = [*0..9,'K'][rut_atendido[0...-2].to_s.reverse.chars.inject([0,0]){|(i,a),n|[i+1,a-n.to_i*(i%6+2)]}[1]%11]
      #if Integer(rut_atendido[-1]) != dv
       # errors.add(:rut_atendido, "Formato de rut mal ingresado")
      #end
        if rut_atendido[0...-2].size != rut_atendido[0...-2].count("0-9")
          #puts "el rut se debe ingresar sin puntos y con guión"
          errors.add(:rut_atendido, "debe ser ingresado sin puntos y con guión")


        else
         #verificado antes del guion

            if rut_atendido.count("k,K") > 1

            errors.add(:rut_atendido, ": Formato de rut mal ingresado. Verificar.") #1

            else

              if dv == 'K'
                if rut_atendido[-1] != 'K' && rut_atendido[-1] != 'k'
                  errors.add(:rut_atendido, ": Formato de rut mal ingresado. Verificar.") #2
                end
              else
                if rut_atendido[-1] != 'K' && rut_atendido[-1] != 'k'
                  if Integer(rut_atendido[-1]) != dv
                    errors.add(:rut_atendido, ": Formato de rut mal ingresado. Verificar.") #3
                  end
                else
                  errors.add(:rut_atendido, ": Formato de rut mal ingresado. Verificar.") #4
                end
              end
            end
          end
    end

    if aspcategory.present? == false
      errors.add(" ", "Complete el campo tipo consulta")
    end

    if codigo_obra.present? == false
      errors.add(" ", "Ingrese una obra")
    end

    if solucion.present? == false
      errors.add(" ", "Complete el campo solucion")
    end

    if descripcion.present? == false
      errors.add(" ", "Complete el campo descripcion")
    end


  end






  def set_atencion_id

    @AS = Asformulary.last

    if(@AS.atencion_id == nil)
      self.atencion_id = 1
      self.numero_atencion = 1
    else
    self.atencion_id = @AS.atencion_id + 1
    self.numero_atencion = 1
    end

  end



  def crear_log_A
  	log = Loga.new(
  		asocial_id: self.id,
  		#user_name: self.user.name,
      user_name: self.lyduser.email,
      	codigo_obra: self.codigo_obra,
      	rut_atendido: self.rut_atendido,
      	nombre_atendido: self.nombre_atendido,
      	apellido_paterno_atendido: self.apellido_paterno,
      	apellido_materno_atendido: self.apellido_materno,
      	aspcategory_name: self.aspcategory.nombre,
      	solucion: self.solucion,
      	estado: self.estado,
      	subcontrato: self.subcontrato,
      	supervisor: self.nombre_supervisor,
      	descripcion: self.descripcion,
      	telefono: self.telefono)
  	log.save!
    #obra = Obra.new(nombre: self.asformulary.user.name, direccion: "direccion2")
    #obra.save!
  end
  def crear_log_B
    if(self.estado == true)
      log = Loga.new(
        asocial_id: self.id,
  		user_name: self.lyduser.email,
      	codigo_obra: self.codigo_obra,
      	rut_atendido: self.rut_atendido,
      	nombre_atendido: self.nombre_atendido,
      	apellido_paterno_atendido: self.apellido_paterno,
      	apellido_materno_atendido: self.apellido_materno,
      	aspcategory_name: self.aspcategory.nombre,
      	solucion: self.solucion,
      	estado: self.estado,
      	subcontrato: self.subcontrato,
      	supervisor: self.nombre_supervisor,
      	descripcion: self.descripcion,
      	telefono: self.telefono)
      log.save!
    end
    #obra = Obra.new(nombre: self.asformulary.user.name, direccion: "direccion2")
    #obra.save!
  end



end

app/controllers/asformularies_controller.rb
class AsformulariesController < ApplicationController
  before_action :set_asformulary, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  #authorize_resource :class => false

  # GET /asformularies
  # GET /asformularies.json
  def index
    #@asformularies = Asformulary.all
    #@asformulary = Asformulary.new(:rut_atendido => params[:rut_atendido])
    @results = Asformulary.search(params[:search]).order('created_at DESC')
    #puts @results[0].rut_atendido
    #puts @results.count
    puts params[:search]
    #puts params[:asformulary][:rut_atendido]


  end

  def get_benefits

    #@company = Benefits.find.params[:company_id]
    #@contacts = @company.contacts

    Rails.logger.warn "#{:areabenefit_id} jajaxxx"
    @contacts = Benefit.where("areabenefit_id = ? and is_active = ? ",params[:areabenefit_id], true)
  end

  def search
    #if(params[:asformulary] && params[:asformulary][:nombre_atendido])

    #end

  end

  # GET /asformularies/1
  # GET /asformularies/1.json
  def show

  if(params[:cerrar])

      theasformulary = Asformulary.find(params[:id])
    if theasformulary.estado != true
      theasformulary.estado = true
      theasformulary.save
    end

      redirect_to asformulary_path

    end

  end

  # GET /asformularies/new
  def new
    if params[:asformulary] && params[:asformulary][:rut_atendido]
      if !params[:asformulary][:rut_atendido].rut_valid?
        redirect_to new_asformulary_path+"/?rut_err=true"
      else
        @asformulary = Asformulary.new

        @employee = Employee.where(:rut => params[:asformulary][:rut_atendido]).where(estado: "A").order('created_at DESC')
        @logloan = Logloan.where(:rut_solicitante => params[:asformulary][:rut_atendido]).order('created_at DESC')

        @rut = @employee[0].rut
        @nombre = @employee[0].nombre
        @obra = @employee[0].cencos
      end
    end
    if params[:asformulary] && params[:asformulary][:rut_atendido] && params[:asformulary][:nombre_atendido] && params[:asformulary][:codigo_obra] && params[:asformulary][:areabenefit_id] && params[:asformulary][:benefit_id]
      @rut = params[:asformulary][:rut_atendido]
      @nombre = params[:asformulary][:nombre_atendido]
      @obra = params[:asformulary][:codigo_obra]
    end
  end

  def checkrut
    redirect_to new_asformulary_path
  end

  def newseg
    #@asformulary = Asformulary.new
    #find-create-set-save
    @newsegAS = Asformulary.find(params[:id])
    theasformulary = Asformulary.find(params[:id])

    if theasformulary.atencion_id == nil
      theasformulary.atencion_id = theasformulary.id
      theasformulary.save
      @asformulary = Asformulary.new(
      rut_atendido: theasformulary.rut_atendido,
      codigo_obra: theasformulary.codigo_obra,
      user_id: theasformulary.user_id,
      nombre_atendido: theasformulary.nombre_atendido,
      aspcategory_id: theasformulary.aspcategory_id,
      solucion: theasformulary.solucion,
      estado: theasformulary.estado,
      subcontrato: theasformulary.subcontrato,
      benefit_id: theasformulary.benefit_id,
      atencion_id: theasformulary.id,
      numero_atencion: theasformulary.numero_atencion+1
      )
    elsif theasformulary.atencion_id != nil
      @asformulary = Asformulary.new(
      rut_atendido: theasformulary.rut_atendido,
      codigo_obra: theasformulary.codigo_obra,
      user_id: theasformulary.user_id,
      nombre_atendido: theasformulary.nombre_atendido,
      aspcategory_id: theasformulary.aspcategory_id,
      solucion: theasformulary.solucion,
      estado: theasformulary.estado,
      subcontrato: theasformulary.subcontrato,
      atencion_id: theasformulary.atencion_id,
      benefit_id: theasformulary.benefit_id,
      numero_atencion: theasformulary.numero_atencion+1
      )
    end



  end


  # GET /asformularies/1/edit
  def edit


  end

  # POST /asformularies
  # POST /asformularies.json
  def create
    if (params[:check])
      redirect_to new_asformulary_path#(rut_atendido: params[:asformulary][:rut_atendido])
    else
      @asformulary = Asformulary.new(asformulary_params)
      @asformulary.lyduser = current_lyduser
      @asformulary.user_id = 1


      respond_to do |format|
        if @asformulary.save


          format.html { redirect_to asformularies_path}#, notice: 'Asformulary was successfully created.' }
          format.json { render :show, status: :created, location: @asformulary }
        else
          format.html { render :new }
          format.json { render json: @asformulary.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /asformularies/1
  # PATCH/PUT /asformularies/1.json
  def update
    respond_to do |format|
      if @asformulary.update(asformulary_params)
        format.html { redirect_to @asformulary, notice: 'Asformulary was successfully updated.' }
        format.json { render :show, status: :ok, location: @asformulary }
      else
        format.html { render :edit }
        format.json { render json: @asformulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asformularies/1
  # DELETE /asformularies/1.json
  def destroy
    @asformulary.destroy
    respond_to do |format|
      format.html { redirect_to asformularies_url, notice: 'Asformulary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asformulary
      @asformulary = Asformulary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asformulary_params
      params.require(:asformulary).permit(:rut_atendido, :codigo_obra, :user_id, :nombre_atendido, :apellido_paterno, :apellido_materno, :aspcategory_id, :solucion, :estado, :subcontrato, :nombre_supervisor, :descripcion, :telefono, :benefit_id, :atencion_id, :numero_atencion, :lyduser_id)
    end
end

app/helpers/asformularies_helper.rb
module AsformulariesHelper
end

app/views/asformularies/_benefit_form.html.erb
<div class="field">
    <div class="field">
        <%= form.label :areabenefit_id, "Area de beneficio" %><br>
        <%= form.collection_select(:areabenefit_id, Areabenefit.where(is_active: true).order("nombre ASC"), :id, :nombre, {:prompt => "Seleccione área de beneficio"},{:class => "areabenefit_selection", style: "width: 87.5%"}) %>
    </div>
    <br>
    <div class="field">
        <%= form.label :benefit_id, "Beneficio" %><br>
        <%= form.collection_select(:benefit_id, Benefit.where(is_active: true).order("nombre ASC"), :id, :nombre, {:prompt => "Seleccione un beneficio"}, {:class => "contact_selection", style: "width: 87.5%"}) %>
    </div>
  </div>

app/views/asformularies/_benefitbutton.html.erb
<% if !@rut.nil? && @rut != "" && !@nombre.nil? && @nombre != "" && !@obra.nil? && @obra != "" %>
  <div class="ui-37-ld" style="width: 90% !important">
    <div class= "row">
      <div class="col-md-4 col-sm-4 col-xs-6 col-mob"> <a href="<%= new_assignbenefit_path(:rut_trabajador => params[:asformulary][:rut_atendido],:obra_id => params[:asformulary][:codigo_obra], :nombre_solicitante => params[:asformulary][:nombre_atendido]) %>" target="_blank" class="bg-green-ld"> <img src='<%= asset_url("trans.png") %>' alt="" />
        <label class="label-ld">Asignar Beneficio</label>
        </a>
      </div>
    </div>
  </div>
<% else %>
  <div class="ui-37-ld" style="width: 90% !important">
    <div class="row">
      <div class="col-md-4 col-sm-4 col-xs-6 col-mob"> <a href="<%= new_assignbenefit_path() %>" target="_blank" class="bg-green-ld"> <img src='<%= asset_url("trans.png") %>' alt="" />
        <label class="label-ld">Asignar Beneficio</label>
        </a>
      </div>
    </div>
  </div>
<% end %>

app/views/asformularies/_loanbutton.html.erb
<% if !@rut.nil? && @rut != "" && !@nombre.nil? && @nombre != "" && !@obra.nil? && @obra != "" %>
  <div class="ui-37-ld" style="width: 90% !important">
    <div class= "row">
      	<div class="col-md-4 col-sm-4 col-xs-6 col-mob"> <a href="<%= new_loanformulary_path(:rut_solicitante => @rut, :nombre_solicitante => @nombre,:obra => @obra) %>" target="_blank" class="bg-green-ld"> <img src='<%= asset_url("trans.png") %>' alt="" />
          <label class="label-ld">Asignar Préstamos</label>
          </a> </div>
    </div>
  </div>
<% else %>
  <div class="ui-37-ld" style="width: 90% !important">
     <div class= "row">
        	<div class="col-md-4 col-sm-4 col-xs-6 col-mob"> <a href="<%= new_loanformulary_path() %>" target="_blank" class="bg-green-ld"> <img src='<%= asset_url("trans.png") %>' alt="" />
            <label class="label-ld">Asignar Préstamos</label>
            </a> </div>
     </div>
  </div>
<% end %>

app/views/asformularies/_search.html.erb
<table> 

              <thead>
                <tr>
                  <th>Nombre trabajador</th>
                  <th>Rut atendido</th>
                  <th>Nombre de obra</th>
                  <th>Telefono</th>
                  <th>Asistente Social</th>
                  <th>Tipo Consulta</th>
                  <th>Solucion</th>
                  <th>Estado</th>
                 
                  <th>Subcontratista?</th>
          

                  <th>Descripcion</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
              <%if params[:search] != "" %>
                <% @results.each do |x|%>
                  <tr>

                    <% oname = Obra.where(codigo: x.codigo_obra) %>

                    <td><%= x.nombre_atendido %></td>
                    <td><%= x.rut_atendido %></td>
                    <% if !oname[0].nil? %>
                    <td><%= oname[0].nombre %></td>
                    <% else %>
                    <td><%= x.codigo_obra %></td>
                    <% end %>
                    <td><%= x.telefono %></td>
                    <td><%# x.lyduser.email %></td>
                    <td><%= x.aspcategory.nombre %></td>
                    <td><%= x.solucion %></td>
                    <% if x.estado == true %>
                    <td><%="Cerrado"%></td>
                    <% else %>
                    <td><%= "Abierto"%></td>
                    <%end%>
                    <% if x.subcontrato == true %>
                    <td><%="SI"%></td>
                    <% else %>
                    <td><%= "NO"%></td>
                    <%end%>
                    
                    <td><%= x.descripcion %></td>
                    <%if can? :show, Asformulary %>
                    <td><%= link_to 'Mostrar', x %></td>
                    <%end%>
      
                    <td><%= link_to 'Agregar Familia', new_familiartrabajador_path(:rut_trabajador => x.rut_atendido ) %></td>
                  
                    <%if can? :destroy, Asformulary %>
                    <td><%= link_to 'Destroy', x, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <%end%>

                    </td>
                  </tr>
                <% end %>
              <%end %>
              </tbody>

              </table>

app/views/asformularies/edit.html.erb
<h1>Actualizar Formulario de Atención Social</h1>

<%= render 'form', asformulary: @asformulary %>

<%= link_to 'Show', @asformulary %> |
<%= link_to 'Back', asformularies_path %>

app/views/asformularies/index.js.erb
$('#asresults').html("<%= escape_javascript(render 'search', locals: { post: @results } ) %>"); 

app/views/asformularies/new.html.erb
<link href='<%= asset_url("css/bootstrap.min.css") %>' rel="stylesheet" type="text/css">
<link href='<%= asset_url("css/font-awesome.min.css") %>' rel="stylesheet">
<link href='<%= asset_url("css/style-55.css") %>' rel="stylesheet">
<link href='<%= asset_url("css2/stylesLD.css") %>' rel="stylesheet" type="text/css">

<h4><%= link_to '<< volver', asformularies_path %></h4>

<div class="container">

      <div class="sidebar1">
        <div align="left">

        <h4>Nuevo Formulario de Atención Social</h4>
        <%= render 'form', asformulary: @asformulary %>
        <%# button_to "Nuevo préstamo", new_loanformulary_path,method: "get", form: {target: '_blank'}, class: "button button1" %>

          <%# link_to(image_tag(asset_url("trans.png"), class: 'bg-green-ld'), new_loanformulary_path,  :method => :get) %>





      </div>

    <!-- end .sidebar1 --></div>


  <div class="contentForm">

    <br>

    <div class="ui-55">
        <div class="sidebar" style="position: fixed;">
          <!-- Nav tabs -->
          <ul class="list-unstyled">
            <li class="active"><a href="#one" role="tab" data-toggle="tab"> Asistencia Social</a></li>
            <li><a href="#two" role="tab" data-toggle="tab"> Beneficios </a></li>
            <li><a href="#three" role="tab" data-toggle="tab"> Prestamos </a></li>
            <li><a href="#four" role="tab" data-toggle="tab"> Capacitaciones </a></li>
            <li><a href="#five" role="tab" data-toggle="tab"> Remuneraciones </a></li>
          </ul>
        </div>
      <div class="mainbar">
        <!-- Tab panes -->

                    <label for="textfield">Resumen Trabajador:
                    <br>
                    <% if params[:asformulary] && params[:asformulary][:rut_atendido] %>
                      <% employee = Employee.where(rut: params[:asformulary][:rut_atendido]).where(estado: "A").order('created_at DESC') %>
                      <% if employee.empty? == false %>
                        <% #employee.each do |emple| %>
                        <tr>
                          <td><%= employee[0].nombre %></td>
                          <td><%= employee[0].rut %></td><br>
                          <% obraname = Obra.where(codigo: employee[0].cencos)  %>
                          <td><%= obraname[0].nombre %></td>
                          <br>

                        </tr>
                        <%#end%>
                      <% else %>
                        <h5>No podemos desplegar un resumen de este trabajador por alguno de los siguientes motivos:</h5>
                        <h6>- El trabajador no posee ficha en Payrroll (subcontrato)</h6>
                        <h6>- El trabajador no se encuentra activo</h6>
                      <%end%>


                    <%end%>



                  </label>
                  <br>


        <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active" id="one">




                  <table >
                  <thead>
                    <tr>
                      <th width="(100/x)%">Fecha</th>
                      <th width="(100/x)%">Tipo Consulta</th>

                      <th width="(100/x)%">Status Caso</th>
                      <th width="(100/x)%">Obra</th>
                      <th width="(100/x)%">Nº Atencion</th>
                      <th width="(100/x)%">Telefono</th>
                      <th width="(100/x)%">Comentario</th>
                    </tr>
                  </thead>
                    <tbody>
                      <% if params[:asformulary] && params[:asformulary][:rut_atendido] %>
                      <% logas = Loga.where(:rut_atendido => params[:asformulary][:rut_atendido]).order('created_at DESC').take(20) %>

                      <% logas.each do |loga| %>
                        <tr>


                          <td><%= loga.created_at.strftime("%d %b %y") %></td>
                          <td><%= loga.aspcategory_name %></td>



                          <% if loga.estado == true %>
                          <td><%="Cerrado"%></td>
                          <% else %>
                          <td><%= "Abierto"%></td>
                          <% end %>


                          <td><%= loga.codigo_obra %></td>
                          <td><%= "N/A" %></td>
                          <td><%= loga.telefono %></td>
                          <td><%= loga.descripcion %></td>

                        </tr>

                      <% end %>
                      <% end %>
                    </tbody>
                  </table>
            </div>
          <div role="tabpanel" class="tab-pane fade" id="two">

          <table >

           <tr>
            <th width="(100/x)%">Beneficio</th>
            <th width="(100/x)%">Rut Trabajador</th>
            <th width="(100/x)%">Rut Beneficiario</th>
            <th width="(100/x)%">Relación</th>
            <th width="(100/x)%">F.Nacimiento</th>
            <th width="(100/x)%">Fecha</th>
            <th width="(100/x)%">Obra</th>
           </tr>
           <tbody>

               <% if params[:asformulary] && params[:asformulary][:rut_atendido] %>
               <% assign = Assignbenefit.where(:rut_trabajador => params[:asformulary][:rut_atendido]).order('created_at DESC').take(20) %>

               <% assign.each do |loga| %>
                        <tr>

                          <td><%= loga.benefit.nombre %></td>
                          <td><%= loga.rut_trabajador %></td>
                          <td><%= loga.rut_beneficiario %></td>
                          <td><%= loga.relacion %></td>
                          <td><%= loga.fecha_nacimiento %></td>

                          <td><%= loga.created_at.strftime("%d %b %y") %></td>

                          <td><%= Obra.find_by_id(loga.obra_id).nombre %></td>


                        </tr>

                      <% end %>



               <% end %>

           </tbody>
        </table>

          </div>
              <div role="tabpanel" class="tab-pane fade" id="three">

                  <table >
                  <thead>
                    <tr>

                      <th width="(100/x)%">Empresa</th>
                      <th width="(100/x)%">Monto Solicitado</th>
                      <th width="(100/x)%">Por pagar</th>
                      <th width="(100/x)%">Motivo</th>
                      <th width="(100/x)%">Estado</th>

                    </tr>
                  </thead>
                    <tbody>
                      <% if params[:asformulary] && params[:asformulary][:rut_atendido] %>
                      <% logloan = Logloan.where(:rut_solicitante => params[:asformulary][:rut_atendido]).order('created_at DESC').take(10) %>
                      <% loan = Loanformulary.where(:rut_solicitante => params[:asformulary][:rut_atendido]).order('created_at DESC').take(20) %>

                      <% logloan.each do |logl| %>
                        <tr>



                          <td><%= logl.empresa %></td>
                          <td><%= number_to_currency(logl.monto_solicitado, unit: "$ ", delimiter: ".", precision: 0) %></td>
                          <td><%= logl.por_pagar %></td>
                          <td><%= logl.motivo_solicitud %></td>
                          <td><%= logl.estado %></td>


                        </tr>
                      <% end %>

                      <% loan.each do |logl| %>
                      <tr>



                          <td></td>
                          <td><%= logl.monto_solicitado %></td>
                          <td></td>
                          <td><%= logl.motivo_solicitud %></td>
                          <td><%= logl.estado %></td>


                        </tr>
                      <% end %>


                      <% end %>
                    </tbody>
                  </table>


              </div>
              <div role="tabpanel" class="tab-pane fade" id="four">

              </div>
              <div role="tabpanel" class="tab-pane fade" id="five">

              </div>
        </div>
      </div>
    </div>

    <!-- Javascript files -->
    <!-- jQuery -->
    <script src='<%= asset_url("jquery.js") %>'></script>
    <!-- Bootstrap JS -->
    <script src='<%= asset_url("bootstrap.min.js") %>'></script>
    <!-- Placeholder JS -->
    <script src='<%= asset_url("placeholder.js") %>'></script>
    <!-- Respond JS for IE8 -->
    <script src='<%= asset_url("respond.min.js") %>'></script>
    <!-- HTML5 Support for IE -->
    <script src='<%= asset_url("html5shiv.js") %>'></script>

    <!-- end .content --></div>

<!-- end .container --></div>

app/views/asformularies/search.html.erb
<table id="as_results"> 

              <thead>
                <tr>
                  <th>Rut atendido</th>
                  <th>Codigo obra</th>
                  <th>Telefono</th>
                  <th>Asistente Social</th>
                  <th>Nombre trabajador</th>
                  <th>Categoria</th>
                  <th>Solucion</th>
                 
                  <th>¿Caso Cerrado?</th>
                  <th>¿Subcontrato?</th>

                  <th>Descripcion</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
              <%#if params[:nombre_atendido] %>
                <%@result.each do |result|%>
                  <tr>
                    <td><%= result.rut_atendido %></td>
                    <td><%= result.codigo_obra %></td>
                    <td><%# result.telefono %></td>
                    <td><%# result.user_name %></td>
                    <td><%= result.nombre_atendido %></td>
                    <td><%# result.aspcategory_name %></td>
                    <td><%# result.solucion %></td>
                    <% if result.estado == true %>
                    <td><%="SI"%></td>
                    <% else %>
                    <td><%= "NO"%></td>
                    <%end%>
                    <% if result.subcontrato == true %>
                    <td><%="SI"%></td>
                    <% else %>
                    <td><%= "NO"%></td>
                    <%end%>
                    
                    <td><%# result.descripcion %></td>
                    <%if can? :show, Asformulary %>
                    <td><%# link_to 'Mostrar', asformulary %></td>
                    <%end%>
                    <%if can? :edit, Asformulary %>
                    <td><%# link_to 'Edit', edit_asformulary_path(asformulary) %></td>
                    <%end%>
                    <%if can? :destroy, Asformulary %>
                    <td><%# link_to 'Destroy', asformulary, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <%end%>

                    </td>
                  </tr>
                <% end %>
              <%#end %>
              </tbody>

              </table>