config/routes.rb
Rails.application.routes.draw do

  resources :logbenefitsfinals do
     collection do
       post 'saveLogFinal', to: "logbenefitsfinals#saveLogFinal"
     end
   end
  resources :familiartrabajadors
  resources :asignarmultiplebeneficios do
    collection do
      get 'get_contacts', to: "asignarmultiplebeneficios#get_contacts"
    end

    collection do
      get 'get_trabajadorporobra', to: "asignarmultiplebeneficios#get_trabajadorporobra"
    end
  end

  resources :logloans
  resources :employees
  resources :assignbenefits
  resources :areabenefits do
    member do
      get :is_active
    end
  end
  resources :loanformularies do
    member do
      get :accept
      get :refuse
      get :filtrar
    end
  end


  devise_for :lydusers
  get '/ld/index', to: 'ld#index'
  get 'ld/crudpannel', to: 'ld#crudpannel'
  get 'ld/beneficiospannel', to: 'ld#beneficiospannel'
  get 'ld/reportspannel', to: 'ld#reportspannel'
  get 'ld/userspannel', to: 'ld#userspannel'
  get 'ld/download_pdf', to: 'ld#download_pdf'
  root to: 'ld#index'
  #get 'asformularies/newseg', to: 'asformularies#newseg', as: 'newseg'


  resources :benefits do
    member do
      get :is_active
    end
  end

  resources :obras
  resources :logas
  resources :epcformularies
  resources :asformularies do
    member do
      get :newseg
      get :checkrut
    end
    collection do
      get 'search', to: "asformularies#search"
      get 'get_benefits', to: "asformularies#get_benefits"
    end
  end

  resources :aspcategories do
    member do
      get :is_active
    end
  end

  resources :users

  resources :pages do
    get :download_pdf
  end


  get '/benefitPanel', to: 'pages#benefitPanel'
  #post '/benefitPanel' => 'pages#indexBenefitPerName'
  post '/logBeneficiosCheckAsistencia', to: 'pages#logBeneficiosCheckAsistencia'
  post '/indexBenefitPerName', to: 'pages#indexBenefitPerName'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord

  # Este código cada vez que existe un nuevo campo, rellena la tabla con remples agregando nuevos employees
  #my_hash = JSON.load(File.read(Rails.root + "app/data/REMPLES.txt"))

  #my_hash.each do |row|
  #  emple = Employee.new
  #  emple.nombre = row['Nombre']
  #  emple.rut = row['Rut']
  #  emple.cencos = row['Cencos']
  #  emple.estado = row['Estado']
  #  emple.cargo = row['Cargo']
  #  emple.save
  #end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
    if(params[:name] == "actualizar")
=begin

      @client = TinyTds::Client.new username: 'proyecta', password: 'proyecta..',
          host: '192.168.1.228', port: 1433
      puts 'Connecting to SQL Server'

      if @client.active? == true then puts 'Done' end

      def execute(sql)
          result = @client.execute(sql)
          result.each
          if result.affected_rows > 0 then puts "#{result.affected_rows} row(s) affected" end
      end

      execute("USE LyD;")

      file = File.open("/var/www/myapp/REMPLESDEF2.txt", 'w')

      results = @client.execute("SELECT * FROM REMPLES;")

      file.write('[')


      results.each do |row|

        jresult = row.to_json

        file.write(jresult + ',')
      end

      file.close

      File.truncate("/var/www/myapp/REMPLESDEF2.txt", File.size("/var/www/myapp/REMPLESDEF2.txt") - 1)

      file = File.open("/var/www/myapp/REMPLESDEF2.txt", 'a')
      file.write(']')
      file.close

      puts "All done."

      @client.close
=end
      Employee.delete_all
      puts "Employees deleted"

      #my_hash = JSON.load(File.read("/var/www/myapp/REMPLESDEF2.txt"))
      my_hash = JSON.load(File.read(Rails.root + "app/data/REMPLES.txt"))

      my_hash.each do |row|


        akey = row['Rut']

        if(akey[0] == " " && akey[1] == " ")
        chars = akey.chars
        chars.delete_at(0)
        chars.delete_at(0)
          if(akey[2] == " ")
            chars.delete_at(0)
          end
        akey = chars.join
        end


        emple = Employee.new
        emple.nombre = row['Nombre']
        emple.rut = akey
        emple.cencos = row['Cencos']
        emple.estado = row['Estado']
        emple.cargo = row['Cargo']
        emple.save
      end

      redirect_to root_path
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:rut, :nombre, :cencos, :estado,:cargo)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rut %>
    <%= form.text_field :rut, id: :employee_rut %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :employee_nombre %>
  </div>

  <div class="field">
    <%= form.label :cencos %>
    <%= form.text_field :cencos, id: :employee_cencos %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado, id: :employee_estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<!--<p id="notice"><%= notice %></p>-->
<link href='<%= asset_url("css/bootstrap.min.css") %>' rel="stylesheet" type="text/css">
<link href='<%= asset_url("css/style-273.css") %>' rel="stylesheet">
<link href='<%= asset_url("css/font-awesome.min.css") %>' rel="stylesheet">
<link href='<%= asset_url("css/style-55.css") %>' rel="stylesheet">
<link href='<%= asset_url("css/style-37.css") %>' rel="stylesheet" type="text/css">
<link href='<%= asset_url("css2/stylesLD.css") %>' rel="stylesheet" type="text/css">


<h1>Trabajadores</h1>

<%= link_to('Actualizar Trabajadores', {:action=>'index', :name => "actualizar"}, data: {:confirm=>'¿Está seguro? Esta operación podria tomar algunos minutos.'}) %>


<div class="ui-302">

<div class="status-two">
          <div class="row">
            <div class="col-md-3">
              <!-- Item Starts -->
              <div class="item">
                <!-- Heading -->
                <h4>Fichas Cargadas</h4>
                <!-- Big Number -->
                <h5 class="green"><%=Employee.count%></h5>
                <!-- Sub-Title -->
              </div>
              <!-- Item Ends -->
            </div>

            </div>
          </div>
        </div>


<br>

<%# link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rut:</strong>
  <%= @employee.rut %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @employee.nombre %>
</p>

<p>
  <strong>Cencos:</strong>
  <%= @employee.cencos %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @employee.estado %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>