config/routes.rb
Rails.application.routes.draw do

  resources :logbenefitsfinals do
     collection do
       post 'saveLogFinal', to: "logbenefitsfinals#saveLogFinal"
     end
   end
  resources :familiartrabajadors
  resources :asignarmultiplebeneficios do
    collection do
      get 'get_contacts', to: "asignarmultiplebeneficios#get_contacts"
    end

    collection do
      get 'get_trabajadorporobra', to: "asignarmultiplebeneficios#get_trabajadorporobra"
    end
  end

  resources :logloans
  resources :employees
  resources :assignbenefits
  resources :areabenefits do
    member do
      get :is_active
    end
  end
  resources :loanformularies do
    member do
      get :accept
      get :refuse
      get :filtrar
    end
  end


  devise_for :lydusers
  get '/ld/index', to: 'ld#index'
  get 'ld/crudpannel', to: 'ld#crudpannel'
  get 'ld/beneficiospannel', to: 'ld#beneficiospannel'
  get 'ld/reportspannel', to: 'ld#reportspannel'
  get 'ld/userspannel', to: 'ld#userspannel'
  get 'ld/download_pdf', to: 'ld#download_pdf'
  root to: 'ld#index'
  #get 'asformularies/newseg', to: 'asformularies#newseg', as: 'newseg'


  resources :benefits do
    member do
      get :is_active
    end
  end

  resources :obras
  resources :logas
  resources :epcformularies
  resources :asformularies do
    member do
      get :newseg
      get :checkrut
    end
    collection do
      get 'search', to: "asformularies#search"
      get 'get_benefits', to: "asformularies#get_benefits"
    end
  end

  resources :aspcategories do
    member do
      get :is_active
    end
  end

  resources :users

  resources :pages do
    get :download_pdf
  end


  get '/benefitPanel', to: 'pages#benefitPanel'
  #post '/benefitPanel' => 'pages#indexBenefitPerName'
  post '/logBeneficiosCheckAsistencia', to: 'pages#logBeneficiosCheckAsistencia'
  post '/indexBenefitPerName', to: 'pages#indexBenefitPerName'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/epcformulary.rb
class Epcformulary < ApplicationRecord
  belongs_to :asformulary
 

  after_create :crear_log_A
  after_update :crear_log_B

  def crear_log_A
  	log = Loga.new(
  		asocial_id: self.asformulary.id, 
  		epcformulary_id: self.id, 
  		user_name: self.asformulary.user.name,
      codigo_obra: self.asformulary.codigo_obra,
      rut_atendido: self.asformulary.rut_atendido,
      rut_atendido_epc: self.rut_atendido,
      nombre_atendido: self.asformulary.nombre_atendido,
      apellido_paterno_atendido: self.asformulary.apellido_paterno,
      apellido_materno_atendido: self.asformulary.apellido_materno,
      aspcategory_name: self.asformulary.aspcategory.nombre,
      solucion: self.asformulary.solucion,
      estado: self.asformulary.estado,
      subcontrato: self.asformulary.subcontrato,
      supervisor: self.asformulary.nombre_supervisor,
      descripcion: self.asformulary.descripcion,
      rut_pariente: self.rut_pariente,
      nombre_pariente: self.nombre_pariente,
      apellido_paterno_pariente: self.apellido_paterno_pariente,
      apellido_materno_pariente: self.apellido_materno_pariente,
      parentezco: self.parentesco,
      empresa: self.empresa,
      comentarios_caso: self.comentarios_caso,
      caso_amerita_epc: self.caso_amerita_epc,
      derivar_a: self.derivar_a,
      fecha_as: self.asformulary.created_at,
      fecha_epc: self.created_at,
      codigo_epc: self.codigo,
      telefono: self.asformulary.telefono)
  	log.save!
    #obra = Obra.new(nombre: self.asformulary.user.name, direccion: "direccion2")
    #obra.save!
  end
  def crear_log_B
    if(self.derivar_a == "cerrar")
      log = Loga.new(
        asocial_id: self.asformulary.id, 
        epcformulary_id: self.id, 
        user_name: self.asformulary.user.name,
        codigo_obra: self.asformulary.codigo_obra,
        rut_atendido: self.asformulary.rut_atendido,
        rut_atendido_epc: self.rut_atendido,
        nombre_atendido: self.asformulary.nombre_atendido,
        apellido_paterno_atendido: self.asformulary.apellido_paterno,
        apellido_materno_atendido: self.asformulary.apellido_materno,
        aspcategory_name: self.asformulary.aspcategory.nombre,
        solucion: self.asformulary.solucion,
        estado: self.asformulary.estado,
        subcontrato: self.asformulary.subcontrato,
        supervisor: self.asformulary.nombre_supervisor,
        descripcion: self.asformulary.descripcion,
        rut_pariente: self.rut_pariente,
        nombre_pariente: self.nombre_pariente,
        apellido_paterno_pariente: self.apellido_paterno_pariente,
        apellido_materno_pariente: self.apellido_materno_pariente,
        parentezco: self.parentesco,
        empresa: self.empresa,
        comentarios_caso: self.comentarios_caso,
        caso_amerita_epc: self.caso_amerita_epc,
        derivar_a: self.derivar_a,
        fecha_as: self.asformulary.created_at,
        fecha_epc: self.updated_at,
        codigo_epc: self.codigo,
        telefono: self.asformulary.telefono)
      log.save!
    end
    #obra = Obra.new(nombre: self.asformulary.user.name, direccion: "direccion2")
    #obra.save!
  end








end

app/controllers/epcformularies_controller.rb
class EpcformulariesController < ApplicationController
  before_action :set_epcformulary, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /epcformularies
  # GET /epcformularies.json
  def index
    @epcformularies = Epcformulary.all
  end

  # GET /epcformularies/1
  # GET /epcformularies/1.json
  def show
  end

  # GET /epcformularies/new
  def new
    @epcformulary = Epcformulary.new

  end

  # GET /epcformularies/1/edit
  def edit
  end

  # POST /epcformularies
  # POST /epcformularies.json
  def create
    @epcformulary = Epcformulary.new(epcformulary_params)
    #@epcformulary.asformulary = @asformulary

    respond_to do |format|
      if @epcformulary.save
        format.html { redirect_to @epcformulary, notice: 'Epcformulary was successfully created.' }
        format.json { render :show, status: :created, location: @epcformulary }
      else
        format.html { render :new }
        format.json { render json: @epcformulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /epcformularies/1
  # PATCH/PUT /epcformularies/1.json
  def update
    respond_to do |format|
      if @epcformulary.update(epcformulary_params)
        format.html { redirect_to @epcformulary, notice: 'Epcformulary was successfully updated.' }
        format.json { render :show, status: :ok, location: @epcformulary }
      else
        format.html { render :edit }
        format.json { render json: @epcformulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epcformularies/1
  # DELETE /epcformularies/1.json
  def destroy
    @epcformulary.destroy
    respond_to do |format|
      format.html { redirect_to epcformularies_url, notice: 'Epcformulary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_epcformulary
      @epcformulary = Epcformulary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def epcformulary_params
      params.require(:epcformulary).permit(:asformulary_id, :rut_atendido, :codigo, :nombre_pariente, :apellido_paterno_pariente, :apellido_materno_pariente, :rut_pariente, :parentesco, :empresa, :codigo_obra, :comentarios_caso, :caso_amerita_epc, :derivar_a)
    end
end

app/helpers/epcformularies_helper.rb
module EpcformulariesHelper
end

app/views/epcformularies/_form.html.erb
<%= form_with(model: epcformulary, local: true) do |form| %>
  <% if epcformulary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(epcformulary.errors.count, "error") %> prohibited this epcformulary from being saved:</h2>

      <ul>
      <% epcformulary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <%= form.hidden_field :asformulary_id, value: params[:asformulary_id] %>

 <div class="field">
    <%= form.label :rut_atendido %>
    <%= form.text_field :rut_atendido, id: :epcformulary_rut_atendido %>
  </div>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.text_field :codigo, id: :epcformulary_codigo %>
  </div>

  <div class="field">
    <%= form.label :nombre_pariente %>
    <%= form.text_field :nombre_pariente, id: :epcformulary_nombre_pariente %>
  </div>

  <div class="field">
    <%= form.label :apellido_paterno_pariente %>
    <%= form.text_field :apellido_paterno_pariente, id: :epcformulary_apellido_paterno_pariente %>
  </div>

  <div class="field">
    <%= form.label :apellido_materno_pariente %>
    <%= form.text_field :apellido_materno_pariente, id: :epcformulary_apellido_materno_pariente %>
  </div>

  <div class="field">
    <%= form.label :rut_pariente %>
    <%= form.number_field :rut_pariente, id: :epcformulary_rut_pariente %>
  </div>

  <div class="field">
    <%= form.label :parentesco %>
    <%= form.text_field :parentesco, id: :epcformulary_parentesco %>
  </div>

  <div class="field">
    <%= form.label :empresa %>
    <%= form.text_field :empresa, id: :epcformulary_empresa %>
  </div>

 <%= form.hidden_field :codigo_obra, value: params[:codigo_obra] %>

  <div class="field">
    <%= form.label :comentarios_caso %>
    <%= form.text_area :comentarios_caso, id: :epcformulary_comentarios_caso %>
  </div>

  <div class="field">
    <%= form.label :caso_amerita_epc %>
    <%= form.check_box :caso_amerita_epc, id: :epcformulary_caso_amerita_epc %>
  </div>

  <div class="field">
    <%= form.label :derivar_a %>
    <%= form.text_field :derivar_a, id: :epcformulary_derivar_a %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/epcformularies/edit.html.erb
<h1>Editing Epcformulary</h1>

<%= form_with(model: @epcformulary, local: true) do |form| %>
  <% if @epcformulary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@epcformulary.errors.count, "error") %> prohibited this epcformulary from being saved:</h2>

      <ul>
      <% @epcformulary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 

  <div class="field">
    <%= form.label :codigo %>
    <%= form.text_field :codigo, id: :epcformulary_codigo %>
  </div>

  <div class="field">
    <%= form.label :nombre_pariente %>
    <%= form.text_field :nombre_pariente, id: :epcformulary_nombre_pariente %>
  </div>

  <div class="field">
    <%= form.label :apellido_paterno_pariente %>
    <%= form.text_field :apellido_paterno_pariente, id: :epcformulary_apellido_paterno_pariente %>
  </div>

  <div class="field">
    <%= form.label :apellido_materno_pariente %>
    <%= form.text_field :apellido_materno_pariente, id: :epcformulary_apellido_materno_pariente %>
  </div>

  <div class="field">
    <%= form.label :rut_pariente %>
    <%= form.number_field :rut_pariente, id: :epcformulary_rut_pariente %>
  </div>

  <div class="field">
    <%= form.label :parentesco %>
    <%= form.text_field :parentesco, id: :epcformulary_parentesco %>
  </div>

  <div class="field">
    <%= form.label :empresa %>
    <%= form.text_field :empresa, id: :epcformulary_empresa %>
  </div>

 <%= form.hidden_field :codigo_obra, value: params[:codigo_obra] %>

  <div class="field">
    <%= form.label :comentarios_caso %>
    <%= form.text_area :comentarios_caso, id: :epcformulary_comentarios_caso %>
  </div>

  <div class="field">
    <%= form.label :caso_amerita_epc %>
    <%= form.check_box :caso_amerita_epc, id: :epcformulary_caso_amerita_epc %>
  </div>

  <div class="field">
    <%= form.label :derivar_a %>
    <%= form.text_field :derivar_a, id: :epcformulary_derivar_a %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>



<%= link_to 'Show', @epcformulary %> |
<%= link_to 'Back', epcformularies_path %>

app/views/epcformularies/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1>Formularios EPC</h1>

<table>
  <thead>
    <tr>
      <th>Formulario AS</th>
      <th>Rut atendido</th>
      <th>Codigo</th>
      <th>Nombre pariente</th>
      <th>Apellido paterno pariente</th>
      <th>Apellido materno pariente</th>
      <th>Rut pariente</th>
      <th>Parentesco</th>
      <th>Empresa</th>
      <th>Codigo obra</th>
      <th>Comentarios caso</th>
      <th>Caso amerita epc</th>
      <th>Derivar a</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @epcformularies.each do |epcformulary| %>
      <tr>
        <td><%= link_to epcformulary.asformulary.id, controller: "asformularies", action: "show", id: epcformulary.asformulary.id %></td>
        <td><%= epcformulary.rut_atendido %></td>
        <td><%= epcformulary.codigo %></td>
        <td><%= epcformulary.nombre_pariente %></td>
        <td><%= epcformulary.apellido_paterno_pariente %></td>
        <td><%= epcformulary.apellido_materno_pariente %></td>
        <td><%= epcformulary.rut_pariente %></td>
        <td><%= epcformulary.parentesco %></td>
        <td><%= epcformulary.empresa %></td>
        <td><%= epcformulary.codigo_obra %></td>
        <td><%= epcformulary.comentarios_caso %></td>
        <td><%= epcformulary.caso_amerita_epc %></td>
        <td><%= epcformulary.derivar_a %></td>
        <td><%= link_to 'Show', epcformulary %></td>
        <td><%= link_to 'Edit', edit_epcformulary_path(epcformulary) %></td>
        <td><%= link_to 'Destroy', epcformulary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Formulario', new_epcformulary_path %> |
<%= link_to 'ir a AS', asformularies_path %>

app/views/epcformularies/new.html.erb
<h1>Nuevo Formulario EPC</h1>

<%= render 'form', epcformulary: @epcformulary %>

<%= link_to 'Back', epcformularies_path %>

app/views/epcformularies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Asformulary:</strong>
  <%= @epcformulary.asformulary.id %>
</p>

<p>
  <strong>Rut atendido:</strong>
  <%= @epcformulary.rut_atendido %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @epcformulary.codigo %>
</p>

<p>
  <strong>Nombre pariente:</strong>
  <%= @epcformulary.nombre_pariente %>
</p>

<p>
  <strong>Apellido paterno pariente:</strong>
  <%= @epcformulary.apellido_paterno_pariente %>
</p>

<p>
  <strong>Apellido materno pariente:</strong>
  <%= @epcformulary.apellido_materno_pariente %>
</p>

<p>
  <strong>Rut pariente:</strong>
  <%= @epcformulary.rut_pariente %>
</p>

<p>
  <strong>Parentesco:</strong>
  <%= @epcformulary.parentesco %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @epcformulary.empresa %>
</p>

<p>
  <strong>Codigo obra:</strong>
  <%= @epcformulary.codigo_obra %>
</p>

<p>
  <strong>Comentarios caso:</strong>
  <%= @epcformulary.comentarios_caso %>
</p>

<p>
  <strong>Caso amerita epc:</strong>
  <%= @epcformulary.caso_amerita_epc %>
</p>

<p>
  <strong>Derivar a:</strong>
  <%= @epcformulary.derivar_a %>
</p>

<%= link_to 'Edit', edit_epcformulary_path(@epcformulary) %> |
<%= link_to 'Back', epcformularies_path %>