config/routes.rb
Rails.application.routes.draw do

  resources :logbenefitsfinals do
     collection do
       post 'saveLogFinal', to: "logbenefitsfinals#saveLogFinal"
     end
   end
  resources :familiartrabajadors
  resources :asignarmultiplebeneficios do
    collection do
      get 'get_contacts', to: "asignarmultiplebeneficios#get_contacts"
    end

    collection do
      get 'get_trabajadorporobra', to: "asignarmultiplebeneficios#get_trabajadorporobra"
    end
  end

  resources :logloans
  resources :employees
  resources :assignbenefits
  resources :areabenefits do
    member do
      get :is_active
    end
  end
  resources :loanformularies do
    member do
      get :accept
      get :refuse
      get :filtrar
    end
  end


  devise_for :lydusers
  get '/ld/index', to: 'ld#index'
  get 'ld/crudpannel', to: 'ld#crudpannel'
  get 'ld/beneficiospannel', to: 'ld#beneficiospannel'
  get 'ld/reportspannel', to: 'ld#reportspannel'
  get 'ld/userspannel', to: 'ld#userspannel'
  get 'ld/download_pdf', to: 'ld#download_pdf'
  root to: 'ld#index'
  #get 'asformularies/newseg', to: 'asformularies#newseg', as: 'newseg'


  resources :benefits do
    member do
      get :is_active
    end
  end

  resources :obras
  resources :logas
  resources :epcformularies
  resources :asformularies do
    member do
      get :newseg
      get :checkrut
    end
    collection do
      get 'search', to: "asformularies#search"
      get 'get_benefits', to: "asformularies#get_benefits"
    end
  end

  resources :aspcategories do
    member do
      get :is_active
    end
  end

  resources :users

  resources :pages do
    get :download_pdf
  end


  get '/benefitPanel', to: 'pages#benefitPanel'
  #post '/benefitPanel' => 'pages#indexBenefitPerName'
  post '/logBeneficiosCheckAsistencia', to: 'pages#logBeneficiosCheckAsistencia'
  post '/indexBenefitPerName', to: 'pages#indexBenefitPerName'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/loga.rb
class Loga < ApplicationRecord

#my_hash = JSON.load(File.read("/home/rem/Escritorio/SqlServerSample/legacylogas2.txt"))

#my_hash.each do |row|
 #loga = Loga.new
 #loga.rut_atendido = row['rut']
 #loga.nombre_atendido = row['nombre']
 #loga.solucion = row['solucion']
 #loga.descripcion = row['solucion']
 #loga.save
#end
  
end

app/controllers/logas_controller.rb
class LogasController < ApplicationController
  before_action :set_loga, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  

  # GET /logas
  # GET /logas.json
  def index
    @logas = Loga.all.order('created_at DESC')


    if(params[:name] == "actualizar")

      Loga.delete_all

      my_hash1 = JSON.load(File.read(Rails.root + "app/data/logasdef2.txt"))


      my_hash1.each do |row|

        log = Loga.new
        log.codigo_obra = row['obra']
        log.rut_atendido = row['rut']
        log.nombre_atendido = row['nombre']
        log.apellido_paterno_atendido = row['apellidop']
        log.apellido_materno_atendido = row['apellidom']
        log.aspcategory_name = row['tipoconsulta']
        log.solucion = row['solucion'] 
        log.descripcion = row['descripcion']
        log.telefono = row['telefono']
        log.created_at = row['fecha']
        log.save
      end

      
      redirect_to root_path

    end




  end

  # GET /logas/1
  # GET /logas/1.json
  def show
  end

  # GET /logas/new
  def new
    @loga = Loga.new
  end

  # GET /logas/1/edit
  def edit
  end

  # POST /logas
  # POST /logas.json
  def create
    @loga = Loga.new(loga_params)

    respond_to do |format|
      if @loga.save
        format.html { redirect_to @loga, notice: 'Loga was successfully created.' }
        format.json { render :show, status: :created, location: @loga }
      else
        format.html { render :new }
        format.json { render json: @loga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logas/1
  # PATCH/PUT /logas/1.json
  def update
    respond_to do |format|
      if @loga.update(loga_params)
        format.html { redirect_to @loga, notice: 'Loga was successfully updated.' }
        format.json { render :show, status: :ok, location: @loga }
      else
        format.html { render :edit }
        format.json { render json: @loga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logas/1
  # DELETE /logas/1.json
  def destroy
    @loga.destroy
    respond_to do |format|
      format.html { redirect_to logas_url, notice: 'Loga was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loga
      @loga = Loga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loga_params
      params.require(:loga).permit(:asocial_id, :epcformulary_id, :user_name, :codigo_obra, :rut_atendido, :nombre_atendido, :apellido_paterno_atendido, :apellido_materno_atendido, :aspcategory_name, :solucion, :estado, :subcontrato, :supervisor, :descripcion, :rut_pariente, :nombre_pariente, :apellido_paterno_pariente, :apellido_materno_pariente, :parentezco, :empresa, :comentarios_caso, :caso_amerita_epc, :derivar_a)
    end
end

app/helpers/logas_helper.rb
module LogasHelper
end

app/views/logas/_form.html.erb
<%= form_with(model: loga, local: true) do |form| %>
  <% if loga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loga.errors.count, "error") %> prohibited this loga from being saved:</h2>

      <ul>
      <% loga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :asocial_id %>
    <%= form.number_field :asocial_id, id: :loga_asocial_id %>
  </div>

  <div class="field">
    <%= form.label :epcformulary_id %>
    <%= form.text_field :epcformulary_id, id: :loga_epcformulary_id %>
  </div>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name, id: :loga_user_name %>
  </div>

  <div class="field">
    <%= form.label :codigo_obra %>
    <%= form.number_field :codigo_obra, id: :loga_codigo_obra %>
  </div>

  <div class="field">
    <%= form.label :rut_atendido %>
    <%= form.text_field :rut_atendido, id: :loga_rut_atendido %>
  </div>

  <div class="field">
    <%= form.label :nombre_atendido %>
    <%= form.text_field :nombre_atendido, id: :loga_nombre_atendido %>
  </div>

  <div class="field">
    <%= form.label :apellido_paterno_atendido %>
    <%= form.text_field :apellido_paterno_atendido, id: :loga_apellido_paterno_atendido %>
  </div>

  <div class="field">
    <%= form.label :apellido_materno_atendido %>
    <%= form.text_field :apellido_materno_atendido, id: :loga_apellido_materno_atendido %>
  </div>

  <div class="field">
    <%= form.label :aspcategory_name %>
    <%= form.text_field :aspcategory_name, id: :loga_aspcategory_name %>
  </div>

  <div class="field">
    <%= form.label :solucion %>
    <%= form.text_field :solucion, id: :loga_solucion %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.check_box :estado, id: :loga_estado %>
  </div>

  <div class="field">
    <%= form.label :subcontrato %>
    <%= form.check_box :subcontrato, id: :loga_subcontrato %>
  </div>

  <div class="field">
    <%= form.label :supervisor %>
    <%= form.text_field :supervisor, id: :loga_supervisor %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, id: :loga_descripcion %>
  </div>

  <div class="field">
    <%= form.label :rut_pariente %>
    <%= form.text_field :rut_pariente, id: :loga_rut_pariente %>
  </div>

  <div class="field">
    <%= form.label :nombre_pariente %>
    <%= form.text_field :nombre_pariente, id: :loga_nombre_pariente %>
  </div>

  <div class="field">
    <%= form.label :apellido_paterno_pariente %>
    <%= form.text_field :apellido_paterno_pariente, id: :loga_apellido_paterno_pariente %>
  </div>

  <div class="field">
    <%= form.label :apellido_materno_pariente %>
    <%= form.text_field :apellido_materno_pariente, id: :loga_apellido_materno_pariente %>
  </div>

  <div class="field">
    <%= form.label :parentezco %>
    <%= form.text_field :parentezco, id: :loga_parentezco %>
  </div>

  <div class="field">
    <%= form.label :empresa %>
    <%= form.text_field :empresa, id: :loga_empresa %>
  </div>

  <div class="field">
    <%= form.label :comentarios_caso %>
    <%= form.text_field :comentarios_caso, id: :loga_comentarios_caso %>
  </div>

  <div class="field">
    <%= form.label :caso_amerita_epc %>
    <%= form.check_box :caso_amerita_epc, id: :loga_caso_amerita_epc %>
  </div>

  <div class="field">
    <%= form.label :derivar_a %>
    <%= form.text_field :derivar_a, id: :loga_derivar_a %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logas/edit.html.erb
<h1>Editing Loga</h1>

<%= render 'form', loga: @loga %>

<%= link_to 'Show', @loga %> |
<%= link_to 'Back', logas_path %>

app/views/logas/index.html.erb
<!--<p id="notice"><%= notice %></p>-->
<% if current_lyduser.admin_role?%>

<h1>LOG Atencion Social</h1>

<%= link_to('Actualizar LOG', {:action=>'index', :name => "actualizar"}, data: {:confirm=>'¿Está seguro? Esta operación podria tomar algunos minutos.'}) %>



<table>
  <thead>
    <tr>

      <th>Obra</th>
      <th>Rut atendido</th>
      <th>Nombre atendido</th>
      <th>Telefono</th>
      <th>Tipo consulta</th>
      <th>Solucion</th>
      <th>Estado</th>
      <th>Subcontratatista?</th>
      <th>Supervisor</th>
      <th>Descripcion</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logas.each do |loga| %>
      <tr>
        <td><%= loga.codigo_obra %></td>
        <td><%= loga.rut_atendido %></td>
        <td><%= loga.nombre_atendido %></td>
        <td><%= loga.telefono %></td>
        <td><%= loga.aspcategory_name %></td>
        <td><%= loga.solucion %></td>
        <td><%= loga.estado %></td>
        <td><%= loga.subcontrato %></td>
        <td><%= loga.supervisor %></td>
        <td><%= loga.descripcion %></td>


        <td><%= link_to 'Show', loga %></td>
        <td><%= link_to 'Edit', edit_loga_path(loga) %></td>
        <td><%= link_to 'Destroy', loga, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loga', new_loga_path %>
<%end%>

app/views/logas/new.html.erb
<h1>New Loga</h1>

<%= render 'form', loga: @loga %>

<%= link_to 'Back', logas_path %>

app/views/logas/show.html.erb
<link href='<%= asset_url("css/bootstrap.min.css") %>' rel="stylesheet" type="text/css">
<link href='<%= asset_url("css/font-awesome.min.css") %>' rel="stylesheet">
<link href='<%= asset_url("css/style-273.css") %>' rel="stylesheet">
<link href='<%= asset_url("css2/stylesLD.css") %>' rel="stylesheet" type="text/css">


<div class="container">
  <div class="content"> 
    <div class="ui-273">
      <div align="center" style="box-shadow:0px 0px 15px rgba(0,0,0,0.1);">


        <p>
  <strong>User name:</strong>
  <%= @loga.user_name %>
</p>

<p>
  <strong>Codigo obra:</strong>
  <%= @loga.codigo_obra %>
</p>

<p>
  <strong>Rut atendido:</strong>
  <%= @loga.rut_atendido %>
</p>

<p>
  <strong>Nombre atendido:</strong>
  <%= @loga.nombre_atendido %>
</p>

<p>
  <strong>Apellido paterno atendido:</strong>
  <%= @loga.apellido_paterno_atendido %>
</p>

<p>
  <strong>Apellido materno atendido:</strong>
  <%= @loga.apellido_materno_atendido %>
</p>

<p>
  <strong>Aspcategory name:</strong>
  <%= @loga.aspcategory_name %>
</p>

<p>
  <strong>Solucion:</strong>
  <%= @loga.solucion %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @loga.estado %>
</p>

<p>
  <strong>Subcontrato:</strong>
  <%= @loga.subcontrato %>
</p>

<p>
  <strong>Supervisor:</strong>
  <%= @loga.supervisor %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @loga.descripcion %>
</p>



<p>
  <strong>Empresa:</strong>
  <%= @loga.empresa %>
</p>


<%= link_to 'Edit', edit_loga_path(@loga) %> |
<%= link_to 'Volver a AS', asformularies_path %>




      </div>
    </div>
  </div>
</div>